config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'home' => 'homes#index'
  get 'home/manager_issues' => 'homes#manager_issues'
  get 'home/assignee_issues' => 'homes#assignee_issues'
  put 'home/change_issue' => 'issues#change'


  resources :users
  resources :issues
  resources :milestones do
    member do
      get :open
      get :close
    end
    collection do
      get :list
    end
  end

=begin
  resources :issues do
    resources :jobs
  end
=end










end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :user
  has_many :issues
  # default_scope -> { order(:due_date) }
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 100 }
  # validates :content, presence: true
  validates :start_date, presence: true
  validates :due_date, presence: true
  validates :m_state, presence: true, length: { maximum: 1 }
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  # before_action :member_logged_in, only: [:select, :quit, :list]
  before_action :set_milestone, only: [:edit, :update, :destroy, :start, :close, :show]
  before_action :manager_logged_in, only: [:index, :new, :create, :edit, :destroy, :update, :start, :close]
  # before_action :logged_in_user, only: :index

  def new
    @milestone = Milestone.new
  end

  def create
    @milestone = current_user.milestones.build(milestone_params)
    if @milestone.save
      flash[:success] = '项目里程碑新建成功!'
      redirect_to home_url
    else
      flash[:warning] = '信息填写有误,请重试'
      render 'new'
      # render 'static_pages/home'
    end
  end

  def show
  end

  def edit
  end

  def update
    # @milestone = Milestone.find_by_id(params[:id])
    if @milestone.update_attributes(milestone_params)
      flash[:info] = '更新成功'
    else
      flash[:warning] = '更新失败'
    end
    # redirect_to milestones_path, flash: flash
    redirect_to milestones_path
  end

  def destroy
    # @milestone = Milestone.find_by_id(params[:id])
    current_user.milestones.delete(@milestone)
    @milestone.destroy
    flash[:success] = "成功删除项目里程碑: #{ @milestone.name }"
    redirect_to milestones_path
  end

  #-------QiaoCode--------
  public

  def start
    # @milestone = Milestone.find_by_id(params[:id])
    if @milestone.update_attributes(m_state: Status::START)
      flash[:info] = '里程碑开启工作模式'
    else
      flash[:warning] = '开通失败'
    end
    redirect_to milestones_path, flash: {:success => "已经成功开启此里程碑:#{ @milestone.name }"}
  end

  def close
    # @milestone = Milestone.find_by_id(params[:id])
    if @milestone.update_attributes(m_state: Status::CLOSE)
      flash[:info] = '里程碑关闭成功'
    else
      flash[:warning] = '里程碑关闭失败'
    end
    redirect_to milestones_path, flash: {:success => "已经成功关闭此里程碑:#{ @milestone.name }"}
  end

  # def select
  #   @course = Course.find_by_id(params[:id])
  #   current_user.courses<<@course
  #   flash={:suceess => "成功选择课程: #{@course.name}"}
  #   redirect_to courses_path, flash: flash
  # end
  #
  # def quit
  #   @course=Course.find_by_id(params[:id])
  #   current_user.courses.delete(@course)
  #   flash={:success => "成功退选课程: #{@course.name}"}
  #   redirect_to courses_path, flash: flash
  # end


  #-------------------------for both teachers and students----------------------

  def index
    @milestone_ids = current_user.milestones.ids
    @issues_count = Hash.new
    @milestone_ids.each do |id|
      @count = Issue.where(milestone_id: id).count
      @issues_count[id] = @count > 1 ? @count.to_s << ' ISSUES' : @count.to_s << ' ISSUE'
    end
    @milestone_items = current_user.milestones.paginate(page: params[:page])
    @milestone_to_do = current_user.milestones.where(m_state: Status::CREATE).paginate(page: params[:page])
    @milestone_doing = current_user.milestones.where(m_state: Status::START).paginate(page: params[:page])
    @milestone_done = current_user.milestones.where(m_state: Status::CLOSE).paginate(page: params[:page])
  end

  private

  def set_milestone
    @milestone = Milestone.find_by_id(params[:id])
  end

  # Confirms a logged-in user as a member.
  def member_logged_in
    unless member_logged_in?
      redirect_to root_path, flash: { danger: '请登陆' }
    end
  end

  def milestone_params
    params.require(:milestone).permit(:name, :context, :start_date, :due_date)
  end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_content.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="title"> To Do </div>
  </div>
</div>

app/views/milestones/_form.html.erb
<%= form_for @milestone, html: {class: 'form-horizontal', role: 'form'} do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label '标题', class: 'col-sm-offset-1 col-sm-2 control-label' %>
      <div class="col-sm-7">
        <%= f.text_field :name, class: 'form-control', required: true, placeholder: '请输入里程碑标题' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label '内容', class: 'col-sm-offset-1 col-sm-2 control-label' %>
      <div class="col-sm-7">
        <div class="field">
          <%= f.text_area :content, class: 'form-control', placeholder: '请输入里程碑内容描述' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label '开始时间', class: 'col-sm-offset-1 col-sm-2 control-label' %>
      <div class="col-sm-7">
          <%= f.date_field :start_date, required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label '结束时间', class: 'col-sm-offset-1 col-sm-2 control-label' %>
      <div class="col-sm-7">
        <%= f.date_field :due_date, required: true %>
      </div>
    </div>

    <div>
      <%= f.submit '提交', class: 'btn btn-success col-sm-offset-5' %>
      <%= link_to '取消', milestones_path, class: 'btn btn-default col-sm-offset-1' %>
    </div>
<% end %>

app/views/milestones/_milestone.html.erb
<div class="panel panel-info">
  <div class="panel-body milestone" id="milestone-<%= milestone.id %>">
    <div class="row">
      <%= link_to milestone.name, milestone_path(milestone), class: 'name' %>
      <% if manager_logged_in? %>
          <%= link_to '新建ISSUE', new_issue_path(milestone_id: milestone.id), class: 'btn btn-info' %>
      <% end %>
    </div>
    <div class="row">
      <%= link_to @issues_count[milestone.id], issues_path(milestone_id: milestone.id), class: 'issues-count' %>
    </div>
    <div class="row timestamp">
      期望完成日期: <%= link_to milestone.due_date , edit_milestone_path(milestone) %>
    </div>
  </div>
</div>

app/views/milestones/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-offset-1 col-md-9">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h4 class="text-center">修改: <%= @milestone.name %></h4>
        </div>
        <div class="panel-body">
          <%= render 'milestones/form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/milestones/index.html.erb
<div class="container-fluid">
  <div class="row" style="padding-top: 5px">
    <div class="col-md-10 col-md-offset-1">
      <% if @milestone_items.blank? %>
          <div class="panel panel-info">
            <div class="panel-body">
              无创建的里程碑项目
            </div>
          </div>
      <% else %>
          <ol class="milestones">
            <%= render @milestone_items %>
          </ol>
          <%= will_paginate @milestone_items %>
      <% end %>
    </div>
  </div>
</div>

app/views/milestones/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h4 class="text-center">新里程碑项目</h4>
        </div>
        <div class="panel-body">
          <%= render 'milestones/form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @milestone.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @milestone.content %>
</p>