config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'home' => 'homes#index'
  get 'home/manager_issues' => 'homes#manager_issues'
  get 'home/assignee_issues' => 'homes#assignee_issues'
  put 'home/change_issue' => 'issues#change'


  resources :users
  resources :issues
  resources :milestones do
    member do
      get :open
      get :close
    end
    collection do
      get :list
    end
  end

=begin
  resources :issues do
    resources :jobs
  end
=end










end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :milestone
  belongs_to :user
  # belongs_to :manager, class_name: 'User'
  # belongs_to :assignee, class_name: 'User'

  # validates :owner_id, presence: true
  validates :assignee_id, presence: true
  validates :name, presence: true, length: { maximum: 100 }
  validates :content, presence: true
  # validates :start_date, presence: true
  validates :due_date, presence: true
  validates :i_process, presence: true, length: { maximum: 2 }
  validates :i_state, presence: true, length: { maximum: 1 }

  # scope
  scope :create_state, -> { where(i_state: Status::CREATE) }
  scope :start_state, -> { where(i_state: Status::START) }
  scope :close_state, -> { where(i_state: Status::CLOSE) }
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  include IssuesHelper

  before_action :set_issue, only: [:change, :show]
  before_action :manager_logged_in, only: [:new, :change]

  def new
    @milestone_issue = Issue.new()
    @milestone_id = params[:milestone_id]
    @member_list = User.where(admin: false, manager: false)
    @member_collect = @member_list.collect {
      |member| [member.name, member.id]
    }
    @user_names = @member_list.pluck(:name)
=begin
    @memberlist.each do |member|
      member.id
      member.name
    end
    @usernames = @memberlist.pluck(:name)
    @userids = @memberlist.pluck(:id)
=end
  end

  def index
    @assignee_ids = Issue.where(milestone_id: params[:milestone_id]).pluck(:assignee_id)
    @assignee_info = assignee_info(@assignee_ids)
    @to_do = Issue.create_state.where(milestone_id: params[:milestone_id])
    @doing = Issue.start_state.where(milestone_id: params[:milestone_id])
    @done = Issue.close_state.where(milestone_id: params[:milestone_id])
  end

  def create
    @issue = current_user.manager_issues.build(issue_params)
    if @issue.save
      flash[:success] = 'ISSUE新建成功!'
      redirect_to home_manager_issues_url
      # redirect_to home_url
    else
      flash[:warning] = '信息填写有误,请重试'
      render 'new'
      # render 'static_pages/home'
    end
  end

  def show
    # @issue_detail = Issue.where(milestone_id: params[:milestone_id], id: params[:id])
  end

  def change
    @source_action_name = params[:source_action]
    if @issue.update_attributes(i_state: params[:state])
      flash[:info] = 'ISSUE状态更新成功'
    else
      flash[:warning] = 'ISSUE状态更新失败'
    end

    if @source_action_name == 'manager_issues'
      redirect_to home_manager_issues_url
    else
      redirect_to home_assignee_issues_url
    end
  end

  private
  def set_issue
    @issue = Issue.find_by_id(params[:id])
  end

  def issue_params
    params.require(:issue).permit(:name, :content, :due_date, :assignee_id, :tag)
        .merge(milestone_id: params[:milestone_id])
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def assignee_info(assignee_ids)
    @assignee_info = Hash.new
    @assignee_users = User.find(assignee_ids)
    @assignee_users.each { |user| @assignee_info[user.id] = user.name }
    return @assignee_info
  end
end

app/views/issues/_form.html.erb
<%= form_for @milestone_issue, url: issues_path(milestone_id: params[:milestone_id]), html: {class: 'form-horizontal', role: 'form'} do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label '标题', class: 'col-sm-offset-1 col-sm-2 control-label' %>
      <div class="col-sm-7">
        <%= f.text_field :name, class: 'form-control', required: true, placeholder: '请输入ISSUE标题' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label '内容', class: 'col-sm-offset-1 col-sm-2 control-label' %>
      <div class="col-sm-7">
        <div class="field">
          <%= f.text_area :content, class: 'form-control', required: true, placeholder: '请输入ISSUE内容' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label '结束时间', class: 'col-sm-offset-1 col-sm-2 control-label' %>
      <div class="col-sm-7">
        <%= f.date_field :due_date, required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label '负责人', class: 'col-sm-offset-1 col-sm-2 control-label' %>
      <div class="col-sm-7">
        <%= f.select :assignee_id, options_for_select(@member_collect),
                     { include_blank: '被指派人'}, class: 'ui dropdown', required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label 'Tag', class: 'col-sm-offset-1 col-sm-2 control-label' %>
      <div class="col-sm-7">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%= f.text_field :tag, class: 'form-control', placeholder: '请输入标签' %>
        </div>
      </div>
    </div>
<!--    <%= hidden_field_tag 'milestone_id', @milestone_id %>
    <%= hidden_field_tag 'user_name_list', @user_names %>-->
    <%= f.submit '提交', class: 'btn btn-success col-sm-offset-4' %>
    <%= link_to '取消', home_path, class: 'btn btn-default col-sm-offset-1' %>
<% end %>

app/views/issues/_issue.html.erb
<% if controller_name == 'issues' and action_name == 'index' %>
    <li class="issuable-row">
        <span>
          <strong><%= link_to issue.name, issue_path(milestone_id: issue.milestone_id, id: issue.id) %></strong>
        </span>
      <div class="issuable-detail">
        <%= link_to issue_path(milestone_id: issue.milestone_id, id: issue.id) do %>
            <span class="issuable-number">#<%= issue.id %></span>
        <% end %>
        <% if issue.tag != '' %>
          <span class="label color-label" style="color: #fff;" +
                <% 'background-color: red' if issue.tag == 'bug' %>
                data-container="body"><%= issue.tag %></span>
        <% end %>
        <span class="assignee-name">负责人: <%= @assignee_info[issue.assignee_id] %></span>
      </div>
    </li>
<% else %>
    <div class="panel panel-info">
      <div class="panel-heading">
        期望完成日期:  <%= issue.due_date %>
        <span class="issue-user">
    <% if action_name == 'manager_issues' %>
        负责人: <%= @assignee_info[issue.assignee_id] %>
    <% end %>
          <% if action_name == 'assignee_issues' %>
        指派人: <%= issue.user.name %>
    <% end %>
    </span>
      </div>
      <div class="panel-body"><%= issue.name %></div>
      <div class="panel-footer text-center">
        <% if issue.i_state == Status::START %>
            <div class="btn-group">
              <%= link_to home_change_issue_path(id: issue.id, state: Status::CREATE, source_action: action_name),
                          method: :put, class: 'btn btn-info btn-sm btn-state' do %>
                  <i class="fa fa-arrow-left"></i>
              <% end %>
              <%= link_to home_change_issue_path(id: issue.id, state: Status::CLOSE, source_action: action_name),
                          method: :put, class: 'btn btn-info btn-sm btn-state' do %>
                  <i class="fa fa-arrow-right"></i>
              <% end %>
            </div>
        <% elsif issue.i_state == Status::CREATE %>
            <%= link_to home_change_issue_path(id: issue.id, state: Status::START, source_action: action_name),
                        method: :put, class: 'btn btn-info btn-sm btn-state' do %>
                <i class="fa fa-arrow-right"></i>
            <% end %>
        <% else %>
            <%= link_to home_change_issue_path(id: issue.id, state: Status::START, source_action: action_name),
                        method: :put, class: 'btn btn-info btn-sm btn-state' do %>
                <i class="fa fa-arrow-left"></i>
            <% end %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/issues/board.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4"><h1 class="text-center">To Do</h1>
      <%= render @to_do %>
    </div>
    <div class="col-md-4"><h1 class="text-center">Doing</h1>
      <%= render @doing %>
    </div>
    <div class="col-md-4"><h1 class="text-center">Done</h1>
      <%= render @done %>
    </div>
  </div>
</div>

app/views/issues/index.html.erb
<div class="container-fluid milestone-content">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="title"> Issues To Do </div>
          <div class="counter"> <%= @to_do.count %> </div>
        </div>
        <ul class="well-list">
          <%= render @to_do %>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="title"> Issues Doing </div>
          <div class="counter"> <%= @doing.count %> </div>
        </div>
        <ul class="well-list">
          <%= render @doing %>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="title"> Issues Done </div>
          <div class="counter"> <%= @done.count %> </div>
        </div>
        <ul class="well-list">
          <%= render @done %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/issues/new.html.erb
<div class="container-fluid container-limited">
  <div class="content" id="content-body">
    <h4 class="page-title">创建新ISSUE</h4>
    <hr>
    <%= render 'issues/form' %>
  </div>
</div>

app/views/issues/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @issue.name %>
</p>