config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'home' => 'homes#index'
  get 'home/manager_issues' => 'homes#manager_issues'
  get 'home/assignee_issues' => 'homes#assignee_issues'
  put 'home/change_issue' => 'issues#change'


  resources :users
  resources :issues
  resources :milestones do
    member do
      get :open
      get :close
    end
    collection do
      get :list
    end
  end

=begin
  resources :issues do
    resources :jobs
  end
=end










end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_sidenav.html.erb
<div class="panel-group" id="accordion">

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">

        <% if manager_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#MilestoneCollapse"><span class="glyphicon glyphicon-user"></span>
              里程碑项目管理</a>
        <% end %>

        <% if member_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#MilestoneCollapse"><span class="glyphicon glyphicon-user"></span>
              任务查看</a>
        <% end %>

      </h4>
    </div>

    <div id="MilestoneCollapse" class="panel-collapse collapse <%= 'in' if ['milestones'].include?(params[:controller]) %>">
      <ul class="list-group">
        <% if manager_logged_in? %>
            <li class="list-group-item">
              <%= link_to milestones_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 已创建的里程碑项目
                  <span class="label label-info pull-right"><%= current_user.milestones.count %></span>
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to new_milestone_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 创建新里程碑
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_top_area.html.erb
<div class="top-area">
  <ul class="nav nav-pills nav-links">
    <% if manager_logged_in? %>
        <li>
          <%= link_to home_path do %>
              创建的里程碑 &nbsp;
              <% if @milestone_count > 0 %>
                  <span class="label label-info pull-right"><%= @milestone_count %></span>
              <% end %>
          <% end %>
        </li>
        <li>
          <%= link_to home_manager_issues_path  do %>
              创建的ISSUE &nbsp;
              <% if @manager_issue_count > 0 %>
                <span class="label label-info pull-right"><%= @manager_issue_count %></span>
              <% end %>
          <% end %>
        </li>
    <% end %>
    <% if member_logged_in? %>
        <li class="disabled"><a href="#">创建的里程碑</a></li>
        <li class="disabled"><a href="#">创建的ISSUE</a></li>
    <% end %>
    <li>
      <%= link_to home_assignee_issues_path do %>
          被指派的ISSUE &nbsp;
          <% if @assignee_issue_count > 0 %>
            <span class="label label-info pull-right"><%= @assignee_issue_count %></span>
          <% end %>
      <% end %>
    </li>
  </ul>
</div>