config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'home' => 'homes#index'
  get 'home/manager_issues' => 'homes#manager_issues'
  get 'home/assignee_issues' => 'homes#assignee_issues'
  put 'home/change_issue' => 'issues#change'


  resources :users
  resources :issues
  resources :milestones do
    member do
      get :open
      get :close
    end
    collection do
      get :list
    end
  end

=begin
  resources :issues do
    resources :jobs
  end
=end










end

app/views/layouts/_content.html.erb
<br>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong> <%= message %></strong>
      </div>
  <% end %>
</div>
<%= yield %>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
  <footer class="container-fluid">
    <p class="text-center">亚信科技新疆电信现场支持 © 2017
    </p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'MIT系统', home_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <!--<li class=<%= 'active' if params[:controller] == 'homes' %>> <%= link_to '主页', home_path %></li>-->
        <% if manager_logged_in? %>
            <li class=<%= 'active' if params[:controller] == 'courses' %>>
              <!-- TODO 当任务更新时 需要更新路径 -->
              <%= link_to '我的管理', home_path %>
            </li>
        <% elsif admin_logged_in? %>
            <li> <%= link_to '控制面板', rails_admin_path %></li>
        <% end %>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li>
              <%= link_to edit_user_path(current_user) do %>
                  <%= current_user.name %> <i class="fa fa-user" aria-hidden="true"></i>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                  退出 <i class="fa fa-sign-out" aria-hidden="true"></i>
              <% end %>
            </li>
        <% else %>
            <li><%= link_to root_path do %>
                  登录 <i class="fa fa-sign-in" aria-hidden="true"></i>
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<% if controller_name!='sessions' %>
<div class="top-area">
  <ul class="nav nav-pills nav-links">
    <% if manager_logged_in? %>
        <li>
          <%= link_to '创建的里程碑', home_path %>
        </li>
        <li>
          <%= link_to '创建的ISSUE', home_manager_issues_path %>
        </li>
    <% end %>
    <% if member_logged_in? %>
        <li class="disabled"><a href="#">创建的里程碑</a></li>
        <li class="disabled"><a href="#">创建的ISSUE</a></li>
    <% end %>
    <li>
      <%= link_to '被指派的ISSUE', home_assignee_issues_path %>
    </li>
    <% if manager_logged_in? %>
        <%= link_to '新建里程碑', new_milestone_path, class: 'btn-sm btn-info btn-new-milestone' %>
    <% end %>
  </ul>
<!--  <% if manager_logged_in? && controller_name == 'milestones' && action_name == 'index' %>
      <div class="btn-new-milestone">
        <%= link_to '新建里程碑', new_milestone_path, class: 'btn-sm btn-info' %>
      </div>
  <% end %>-->
</div>
<% end %>





app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %> <%= 'body-background' if params[:controller]=='sessions' %>">
<%= render partial: 'layouts/header' %>
<%= render partial: 'layouts/content' %>
<%= render partial: 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>